#! /bin/bash

. "${HOME}/.cache/wal/colors.sh"

sxhkd &
picom &
./config/bspwm/panel.sh &
wal -R &
kdeconnect-indicator &
plank &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	3
bspc config window_gap		9
bspc config top_padding		0
bspc config focus_follows_pointer	true


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false


bspc config single_monocle	true


bspc config pointer_modifer	mod1 #alt
bspc config pointer_action1	resize_corner
bspc config pointer_follows_monitor true

bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true



bspc config normal_border_color  "$color1"
bspc config active_border_color	"$color2"
bspc config focused_border_color	"$color15"	
bspc config presel_feedback_color		"$color1"
